### ISSUE TITLE
Readme with broken links

### ISSUE THREAD

**Issue by dougolima** [Farfetch/kafkaflow-retry-extensions#52]
The readme file has 2 "broken" links:

![image](https://user-images.githubusercontent.com/233064/135633046-b99f89e8-2d9e-4bc0-967e-57a3dd4569ec.png)

**Comment by luispfgarces** [comment]
We will wait for the structure definition of documentation on #4.
We have discussed that the samples link should point towards an intermediate documentation structure and that documentation points toward the samples' source code on the repository.

**Comment by luispfgarces** [comment]
Also change README file to set the requirements to .NET Standard 2.0 instead of .NET Core 2.1.

**Comment by jdromeiro** [comment]
This issue has been fixed with the creation of the wikipage.
