### ISSUE TITLE
Strategy to rotate the retry queues

### ISSUE THREAD

**Issue by rodrigobelo** [Farfetch/kafkaflow-retry-extensions#57]
### Is your request related to a problem you have?

Allow defining a sliding strategy that always orders by last execution.

As default currently, we always execute the top 1024 queues. The idea is to have a constantly changing list of execution (on rotation).

### Describe the solution you'd like

In order to accomplish this, we can order the retrieved queues by last execution date, to ensure the older retried queues are executed first.

### Are you able to help bring it to life and contribute with a Pull Request?

Yes

**Comment by luispfgarces** [comment]
As confirmed by @fernando-a-marins, this is already implemented and ensured by the KafkaFlow Retry extension.
