### ISSUE TITLE
Change log level of the simple retry to verbose

### ISSUE THREAD

**Issue by sergiosimoes025** [Farfetch/kafkaflow-retry-extensions#85]
When the retry is ongoing the log level of the retry attempt is an error. 

I suggest changing the log level to verbose, and only when the retries are all done, an error must be raised.

https://github.com/Farfetch/kafka-flow-retry-extensions/blob/e6e7d414f96de05aec6abda680e169a475a27da0/src/KafkaFlow.Retry/Simple/RetrySimpleMiddleware.cs#L54

**Comment by luispfgarces** [comment]
Closing issue. Please refer to https://github.com/Farfetch/kafkaflow-retry-extensions/pull/86#issuecomment-1419436585 for further details.
